
/* This file was automatically generated by pclu.*/

#include "pclu_err.h"
#include "pclu_sys.h"


CLUREF STR_UNIX;
static int _operating_system_own_init = 0;

/**** BEGIN PROCEDURE _operating_system ****/

errcode _operating_system(ret_1)
CLUREF *ret_1;
    {
    errcode err;
    errcode ecode2;
        if (_operating_system_own_init == 0) {
        stringOPcons("UNIX", CLU_1, CLU_4, &STR_UNIX);
        _operating_system_own_init = 1;
    }
    enter_proc(2);

  LINE(3);
    {
    {
    ret_1->str = STR_UNIX.str;
    }
    {signal (ERR_ok);}}
    goto end_0;
    ex_0:
        {
            if (err == ERR_failure) {signal(ERR_failure);}
            elist[0] = _pclu_erstr(err);
            {signal(ERR_failure);}
        }
    end_0: elist[0].str = no_return_values_STRING;
        {signal(ERR_failure);}
    }

/**** END PROCEDURE _operating_system ****/


extern errcode _host_name();

/**** BEGIN PROCEDURE _host_system ****/

errcode _host_system(ret_1)
CLUREF *ret_1;
    {
    errcode err;
    errcode ecode2;
    enter_proc(6);

  LINE(7);
    {
    {
    CLUREF T_1_1;
    err = _host_name(&T_1_1);
    if (err != ERR_ok) goto ex_0;
    ret_1->num = T_1_1.num;
    }
    {signal (ERR_ok);}}
    goto end_0;
    ex_0:
        {
            if (err == ERR_failure) {signal(ERR_failure);}
            elist[0] = _pclu_erstr(err);
            {signal(ERR_failure);}
        }
    end_0: elist[0].str = no_return_values_STRING;
        {signal(ERR_failure);}
    }

/**** END PROCEDURE _host_system ****/

